---
title: "Week7InClassWork.rmd"
author: "Peyton Hall"
date: "02/22/2024"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)

#install.packages("tidyverse")
library(tidyverse)
```
```{r}
head(cars)

cars %>% head() # use pipe operator, then print six lines

round(sqrt(length(InsectSprays$count)),digits = 2)

InsectSprays$count%>% 
  length() %>% 
  sqrt() %>%
  round(digits = 2)
```

# Select()

```{r}
df<-data.frame(A=1:5, B=6:10, C=11:15)

df2<-select(df, A, C)

df3<-df%>%
  select(B,C)

df4<-df%>%
  select(-C)


```

# Example

```{r}
str(Orange)

Orange2<-Orange %>% 
  select(Tree, circumference)
```

# filter() function

```{r}
df5<-filter(df,A>2)

df%>%filter(A>2)

df
df%>%filter(A>2,B<8)

df%>%filter(A>2 | B<7)

```

# Example

```{r}
exl<-Orange%>% filter(Tree=="1")

ex2<-Orange%>% filter(Tree=="1", circumference>100)

ex3<-Orange%>% filter(Tree==1 & Tree==2 & Tree==3 & circumference>100)

ex4<-Orange%>% filter((Tree==1|Tree==2|Tree==3) & circumference>100)

ex4<-Orange%>% filter(Tree=="1"|Tree=="2"|Tree=="3", circumference>100)
ex5<-Orange%>% filter(Tree %in% c("1","2","3") & circumference>100)

df%>%filter(A%in%c(1,3,5))


```

